#INCLUDE "p16f877a.inc"
	__CONFIG _CP_OFF & _WDT_OFF & _PWRTE_OFF & _BODEN_OFF & _LVP_OFF & _HS_OSC

	ORG	0X00

CONFI	BSF	STATUS,RP0
	MOVLW	B'0000001' ;Buzzer fan and LM35, rest unused
	MOVWF	TRISA
	MOVLW	B'11110000'
	MOVWF	TRISB    ; PORTB first 4 INPUT, last 4 OUTPUT
	MOVLW	B'11111110'
	MOVWF	TRISC  ;all input but TX, MISSING CX TXL
	MOVLW	0X00
	CLRF	TRISD    ; PORTD   OUTPUT for LCD DATA
	MOVLW	B'000'
	MOVWF	TRISE  ; LCD control
	BCF	STATUS,RP0

INIT	CLRF	PORTD
	MOVLW	B'000000'
	MOVWF	PORTA
	BCF	PORTB,7
	BCF	PORTB,6
	BCF	PORTB,5
	BCF	PORTB,4
	;MISSING CX TX
	CLRF	PORTE

MAIN
	END
